name: Build and Verify 
# Builds, tests, and publishes dev builds of Android SDKs. The CD destination and CI configuration are handled by your gradle files. You only invoke tasks here
# ** Building multiple modules? If one depends on another, you'll have to build the dependencies in one step and the rest in another. 
#      See below for more info 
# REPOSITORY SECRETS REQUIRED: (see https://docs.github.com/en/actions/security-guides/encrypted-secrets) 
#   "ARTIFACTORY_EMAIL": an artifactory account email with publish permissions for the destination artifactory
#   "ARTIFACTORY_PASSWORD": the password for the artifactory account

on:
  push:

jobs:
  build-aars:
    name: Build & Publish Dev Artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # This step will build all modules configured for publication and publish them
      # Does your project publish multiple libraries in a dependency chain? You'll have to add another copy of this step and build the dependency in the first one
      - name: Build and Publish to Dev Repo
        uses: gradle/gradle-build-action@v3.1.0
        with:
          arguments: artifactoryPublish
        env:
          ORG_GRADLE_PROJECT_artifactory_user: ${{ secrets.ARTIFACTORY_EMAIL }}
          ORG_GRADLE_PROJECT_artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          GH_USER: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

  emulator-tests:
    name: Run Instrumentation Tests (ones that work well on emulators only)
    runs-on: ubuntu-latest
    needs: build-aars

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build-aars

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Unit Tests
        uses: gradle/gradle-build-action@v3.1.0
        with:
          arguments: test
  
