apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  concurrency: 1
  retries: 3
    
  metadata:
    tags:
      - mux-player
      - android
      - data
    build: "Branch/Tag: TEMPLATE_BRANCH"
espresso:
  app: automatedtests/build/outputs/apk/debug/automatedtests-debug.apk
  testApp: automatedtests/build/outputs/apk/androidTest/debug/automatedtests-debug-androidTest.apk
suites:
  - name: 'TEMPLATE_BRANCH-TEMPLATE_COMMIT Player Android Data Automation'
    devices:
      - name: Google Pixel.*

  # Maybe this will work
  - name: 'TEMPLATE_BRANCH-TEMPLATE_COMMIT Player Android Data Automation'
    testApp: library/build/outputs/apk/androidTest/debug/library-debug-androidTest.apk
    emulators:
      - name: 'TEMPLATE_BRANCH-TEMPLATE_COMMIT Player Android Cache Instrumentation'
        orientation: portrait
        platformVersions:
          - "14.0"
